language: c

sudo: false

os:
  - linux

compiler:
  - clang

notifications:
  email:
    recipients:
      - alex.shaw.as@gmail.com
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

cache:
  - apt

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data
      - ninja-build
      - build-essential
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libelfg0-dev
      - autoconf
      - bison
      - flex
      - libtool
      - binutils
      - binutils-gold
      - binutils-dev
      - gawk
      - texinfo
      - s3cmd

env:
  matrix:
    - CMAKE_BUILD_TYPE="Release" CPACK_GENERATOR="TBZ2"

script:
  - ./.travis/build.sh

after_failure:
  - ./.travis/onerror.sh

deploy:
  provider: s3
  access_key_id: AKIAJCZVPF7JVCZ3HLUA
  secret_access_key:
    secure: iEZgq0bcBASItBQ2XuLjGvMw5ebuiqAuLeOkwODAYzxTWw9swq+qRwzI0RhwceN4JYfx/eluXVtF2+Zoi/bPOwQEAX9Nsh+wutYepA3/KCxGMBfaaCc1Oe3xba0JZVg49gsjrpCHDv0SRpYnq8NSotsQHbV6S8002y+o6FxMum0=
  bucket: openctr-upload-test
  local-dir: dist
  acl: private
