################################################################################
# OpenCTR - A free and open-source SDK for Nintendo 3DS homebrew.
#
# Copyright (C) 2015 The OpenCTR Project.
#
# This file is part of OpenCTR.
#
# OpenCTR is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3 as published by
# the Free Software Foundation.
#
# OpenCTR is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenCTR. If not, see <http://www.gnu.org/licenses/>.
################################################################################

language: c

sudo: false

compiler:
  - clang

os:
  - linux
  - osx

cache:
  - apt

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - clang-3.6
      - build-essential
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libelfg0-dev

env:
  global:
    - secure: "bqSyuIxvBz9ORiSanVzcLaxhChcZb7ia2zUVYQZT+GUEShZgbxDdSFLEJceIa58iWThUobGMRAJtv+u4Jn3Fzcbh0hZvEMOu1/T4/xq56shneZxfWrO0udOr3AIe+65ZakrSIq2jPS4EkMw+lFPM7XkQQs1HxmC74DUnsEJRKw8="
    - secure: "nGx9wzUK9ox/+v4JIVrtyV3DCwyeUUEaJ5a319NgioKSVxz1NvH3+US+bE4/CQNvfieNsNIOK3co2N9cHMGKqYeVeYZ9kWyLw3EtM2S/QUfyLta9zpHH5TKFfnJT8vXoJVGcRYfac80RcfnPdRiTq6TPml12ehXYkFFDYnMrPeo="
    - SOURCE_DIR=${PWD}
    - BUILD_DIR=${SOURCE_DIR}/build
    - DIST_DIR=${SOURCE_DIR}/dist
    - TRAVIS_DIR=${SOURCE_DIR}/.travis

before_script:
  - ${TRAVIS_DIR}/setup.sh

script:
  - cmake --build ${BUILD_DIR} --target all

after_success:
  - cmake --build ${BUILD_DIR} --target package

after_failure:
  - cat ${BUILD_DIR}/toolchain/src/newlib-build/config.log

before_deploy:
  - rm -rf ${DIST_DIR}/_CPack_Packages

deploy:
  provider: s3
  access_key_id: "${S3_ACCESS_KEY}"
  secret_access_key: "${S3_SECRET_KEY}"
  bucket: "openctr-upload-test"
  skip_cleanup: true
  local-dir: "${DIST_DIR}"
