language: c

sudo: false

os:
  - linux

compiler:
  - clang

cache:
  - apt

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data
      - ninja-build
      - build-essential
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libelfg0-dev
      - autoconf
      - bison
      - flex
      - libtool
      - binutils
      - binutils-gold
      - binutils-dev
      - gawk
      - texinfo
      - s3cmd

env:
  global:
    - secure: "bqSyuIxvBz9ORiSanVzcLaxhChcZb7ia2zUVYQZT+GUEShZgbxDdSFLEJceIa58iWThUobGMRAJtv+u4Jn3Fzcbh0hZvEMOu1/T4/xq56shneZxfWrO0udOr3AIe+65ZakrSIq2jPS4EkMw+lFPM7XkQQs1HxmC74DUnsEJRKw8="
    - secure: "nGx9wzUK9ox/+v4JIVrtyV3DCwyeUUEaJ5a319NgioKSVxz1NvH3+US+bE4/CQNvfieNsNIOK3co2N9cHMGKqYeVeYZ9kWyLw3EtM2S/QUfyLta9zpHH5TKFfnJT8vXoJVGcRYfac80RcfnPdRiTq6TPml12ehXYkFFDYnMrPeo="
  matrix:
    - CMAKE_BUILD_TYPE="Release" CPACK_GENERATOR="TBZ2"

before_script:
  - mkdir /home/travis/build/OpenCTR/OpenCTR/build
  - cd /home/travis/build/OpenCTR/OpenCTR/build
  - echo cmake
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCPACK_GENERATOR=${CPACK_GENERATOR}
    
script:
  - ./.travis/build.sh

after_failure:
  - ./.travis/onerror.sh
