language: c

sudo: false

os:
  - linux

compiler:
  - clang

cache:
  - apt

addons:
  artifacts: true
  s3_region: "us-east-1"
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data
      - ninja-build
      - build-essential
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libelfg0-dev
      - autoconf
      - bison
      - flex
      - libtool
      - binutils
      - binutils-gold
      - binutils-dev
      - gawk
      - texinfo
      - binutils-mingw-w64-i686
      - binutils-mingw-w64-x86-64
      - g++-mingw-w64-i686
      - g++-mingw-w64-x86-64
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-x86-64

env:
  global:
    - secure: "bqSyuIxvBz9ORiSanVzcLaxhChcZb7ia2zUVYQZT+GUEShZgbxDdSFLEJceIa58iWThUobGMRAJtv+u4Jn3Fzcbh0hZvEMOu1/T4/xq56shneZxfWrO0udOr3AIe+65ZakrSIq2jPS4EkMw+lFPM7XkQQs1HxmC74DUnsEJRKw8="
    - secure: "nGx9wzUK9ox/+v4JIVrtyV3DCwyeUUEaJ5a319NgioKSVxz1NvH3+US+bE4/CQNvfieNsNIOK3co2N9cHMGKqYeVeYZ9kWyLw3EtM2S/QUfyLta9zpHH5TKFfnJT8vXoJVGcRYfac80RcfnPdRiTq6TPml12ehXYkFFDYnMrPeo="
    - SOURCE_DIR=/home/travis/build/OpenCTR/OpenCTR
    - BUILD_DIR=/home/travis/build/OpenCTR/OpenCTR/build
    - DIST_DIR=/home/travis/build/OpenCTR/OpenCTR/dist
  matrix:
    - CMAKE_BUILD_TYPE="Release" CPACK_GENERATOR="TBZ2"

before_script:
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake ..
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCPACK_GENERATOR=${CPACK_GENERATOR}
    -DENABLE_DOC=OFF
    -DENABLE_LIBCTRU=OFF
    -DENABLE_LIBCTR=ON
    -DENABLE_LLVM=OFF
    -DENABLE_GCC=ON

script:
  - cmake --build ${BUILD_DIR} --config ${CMAKE_BUILD_TYPE} --target OpenCTR

after_success:
  - cpack

before_deploy:
  - rm -rf ${DIST_DIR}/_CPack_Packages

deploy:
  provider: s3
  access_key_id: "${S3_ACCESS_KEY}"
  secret_access_key: "${S3_SECRET_KEY}"
  bucket: "openctr-upload-test"
  skip_cleanup: true
  local-dir: "${DIST_DIR}"
