
language: c

sudo: false

os:
  - linux

compiler:
  - clang

notifications:
  email:
    recipients:
      - alex.shaw.as@gmail.com
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

cache:
  - apt

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data
      - ninja-build
      - build-essential
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libelfg0-dev
      - autoconf
      - bison
      - flex
      - libtool
      - binutils
      - binutils-gold
      - binutils-dev
      - gawk
      - texinfo

env:
  global:
    - CMAKE_ARGS="-DENABLE_DOC=OFF -DENABLE_LIBCTRU=OFF -DENABLE_LIBCTR=ON -DENABLE_LLVM=OFF -DENABLE_GCC=ON"
  matrix:
    - CMAKE_BUILD_TYPE="Release"

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE $CMAKE_ARGS ..

script:
  - cmake --build . --config $CMAKE_BUILD_TYPE --target OpenCTR

after_failure:
  - for i in `find /home/travis/build/OpenCTR/OpenCTR/build -iname "*-err.log"`; do echo "$i"; cat "$i"; done
