
language: 
  - c

compiler:
  - gcc

notifications:
  email:
    recipients:
      - alex.shaw.as@gmail.com
    on_success: always
    on_failure: always
    on_start: never

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y wget
  - sudo apt-get install -y cmake
  - sudo apt-get install -y rpm
  - sudo apt-get install -y binutils
  - sudo apt-get install -y gawk
  - sudo apt-get install -y libgmp-dev
  - sudo apt-get install -y libmpfr-dev
  - sudo apt-get install -y libmpc-dev
  - sudo apt-get install -y libcloog-isl-dev
  - sudo apt-get install -y libcloog-ppl-dev 
  - sudo pip install sphinx

install:
  - wget -O "/tmp/cmake-3.0.1-Linux-i386.tar.gz" "http://www.cmake.org/files/v3.0/cmake-3.0.1-Linux-i386.tar.gz"
  - tar -xvf "/tmp/cmake-3.0.1-Linux-i386.tar.gz"
  - export PATH=$PWD/cmake-3.0.1-Linux-i386/bin/:$PATH

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -DENABLE_DOC=ON -DENABLE_UPLOAD=ON -DENABLE_LOG=OFF -DCPACK_GENERATOR="TBZ2;RPM;DPKG"

script:
  - make
