language: c

sudo: false

compiler:
  - clang

os:
  - linux
  - osx

cache:
  - apt

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - g++-5
      - cmake
      - cmake-data
      - ninja-build
      - clang-3.6
      - build-essential
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libelfg0-dev
      - autoconf
      - bison
      - flex
      - libtool
      - binutils
      - binutils-gold
      - binutils-dev
      - gawk
      - texinfo

env:
  global:
    - secure: "bqSyuIxvBz9ORiSanVzcLaxhChcZb7ia2zUVYQZT+GUEShZgbxDdSFLEJceIa58iWThUobGMRAJtv+u4Jn3Fzcbh0hZvEMOu1/T4/xq56shneZxfWrO0udOr3AIe+65ZakrSIq2jPS4EkMw+lFPM7XkQQs1HxmC74DUnsEJRKw8="
    - secure: "nGx9wzUK9ox/+v4JIVrtyV3DCwyeUUEaJ5a319NgioKSVxz1NvH3+US+bE4/CQNvfieNsNIOK3co2N9cHMGKqYeVeYZ9kWyLw3EtM2S/QUfyLta9zpHH5TKFfnJT8vXoJVGcRYfac80RcfnPdRiTq6TPml12ehXYkFFDYnMrPeo="
    - SOURCE_DIR=${PWD}
    - BUILD_DIR=${SOURCE_DIR}/build
    - DIST_DIR=${SOURCE_DIR}/dist
    - TRAVIS_DIR=${SOURCE_DIR}/.travis

matrix:
  allow_failures:
    - os: osx

before_script:
  - ${TRAVIS_DIR}/setup.sh

script:
  - cmake --build ${BUILD_DIR} --target all

after_success:
  - cmake --build ${BUILD_DIR} --target package

before_deploy:
  - rm -rf ${DIST_DIR}/_CPack_Packages

deploy:
  provider: s3
  access_key_id: "${S3_ACCESS_KEY}"
  secret_access_key: "${S3_SECRET_KEY}"
  bucket: "openctr-upload-test"
  skip_cleanup: true
  local-dir: "${DIST_DIR}"
