
language: c

sudo: false

os:
  - linux

compiler:
  - clang

notifications:
  email:
    recipients:
      - alex.shaw.as@gmail.com
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

cache:
  - apt

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang
      - cmake
      - cmake-data
      - gcc-4.9
      - g++-4.9
      - ninja-build
      - build-essential
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - autoconf
      - bison
      - flex
      - libtool
      - binutils
      - binutils-gold
      - binutils-dev
      - gawk
      - texinfo

env:
  matrix:
    - CMAKE_CC="/usr/bin/clang" CMAKE_CXX="/usr/bin/clang++" CMAKE_BUILD_TYPE="Release"

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_C_COMPILER=$CMAKE_CC -DCMAKE_CXX_COMPILER=$CMAKE_CXX -G Ninja ..

script:
  - cmake --build . --config $CMAKE_BUILD_TYPE --target gcc

after_failure:
  - for i in `find /home/travis/build/OpenCTR/OpenCTR/build/toolchain -iname "*.log"`; do echo "$i"; cat "$i"; done
